const defaultData = {
        data: {
          table: [
            {
              CUST_NO: "",
              SLS_REP: "",
              TKT_NO: "",
              TERMS_COD: "",
              CUST_PO_NO: "",
              TKT_DAT: "",
              DESCR: "",
              ITEM_NO: "",
              BILL_CITY: null,
              BILL_EMAIL_ADRS_1: "",
              BILL_NAM: "",
              BILL_PHONE_1: "",
              BILL_STATE: null,
              BILL_ZIP_COD: null,
              SHIP_CITY: null,
              billAddress: "",
              SHIP_VIA_COD: "",
              SHIP_DAT: "",
              SHIP_NAM: "",
              SHIP_PHONE_1: "",
              SHIP_STATE: null,
              SHIP_ZIP_COD: null,
              shipAddress: "",
              hours: 0,
              SalesQty: 0,
              //NOTE_DAT: "",
              //NOTE_TXT: "",
              USR_APPT_DAT: null,
              USR_APPT_TIM: null,
              USR_CUSTOMER_OWN_PARTS: null,
              USR_EXTERIOR: null,
              USR_ID: "",
              USR_LIC_PLATE: "",
              USR_MAKE: "",
              USR_MODEL: "",
              USR_ODOMETER_IN: "",
              USR_ODOMETER_OUT: null,
              USR_RETAIN_PARTS: null,
              USR_SERVICE_IN_DAT: null,
              USR_SERVICE_IN_TIM: null,
              USR_SERVICE_OUT_DAT: null,
              USR_SERVICE_OUT_TIM: null,
              USR_SERVICE_TYP: "",
              USR_VEHICLE_INFO: "",
              USR_VIN_NO: "",
              USR_WHEEL_LOCK: null,
              USR_YR: '',
            }
          ],
          notes: [{
            NOTE_DAT: "",
            NOTE_TXT: "",
          }],
          barcode: { base64: null },
          signature: {
            signature: '',
            dateSigned: '',
          },
        },
}

export default defaultData;